apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  name: covid19-per-capita
  namespace: default
spec:

# Insert ssh-keys for allowing users to git push
  authorizedKeys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCs1JZA0pHL1mxLCft4XgQHSvcx3aPTsR2HbRWbh0bEWELX/o2AbM0SdZSku+9SQhAALoeWFSgsptiTa3KPhCyYQRA/Q2UfCsoFXn5Nfr6OFWR2LnP5t6q9cJM2WkFdXr00lENmy6XWuBhxTBB6AQ5am6+B2jmhSMEuHyWH87fLg1tWtpxRuxPMmwyQCGtNSGk3NJQ3KdlKQqqtMSrOD/yuK60IvTZGaMF5IQkVJVqqHaa1DMzbwq8++OuG2jYg7V8S3z1nz/RCLr9mfEKZipTkrJctJYR414FdIQs45JaKpuieGAfsP8B9yT7DS6eZsyadj1VtvqsJNs7W7RQ/iWIgiuBt0UvBINGRkN18wK3PN86iI5lCjzBTOZIemLvkjbeAfuiPKNse4JyWf2DReV22LS0W05XL392Bm4Sp/7G26lGUpenFO511ExdEGKxBYurLJGBFLgGuTXTlOBcGd9a3G8Ho8oAW8SDdZ0bccG2dTdvhXAdragx3UN5sHF4Sx5p3698iyYRIEA7HT1sboajWkC0ievGWkuWJAAifHOpEqmLWia5KeWuq3dsN6Q/r2ID0uNKs/DhOgucmKBjR1jDduZtVrQWA6sATN/l8sa5gcN5/L5Hfx87Kkz3Q1l7BaPskE7jwuoPBaSHD/kJEYbrWSHqGZdOw9o1oJYPJ02aNQQ== platy@njk.onl
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDExpPmz35Q+QbZxoxBdG6QGACgCA/UqvFjcu0JVJIY17XStHWOjj36z37N0xwInPhTh5+yL9voC6G2u+pWlnZ7j+HK5L0eyEounkuq6cpzILsjDji0xaUlsyfRUYSAwvFa32qPre2G+7w6SRIZelQ4P6FYOc1wrgGrY1mFe/cEJnVAw+ZuGemSbW5rV8MYJGCzpjutWSyDvkL1axdDP1x83MfIcx8asUQATOyA3G0kCh6p4OlO53wPTEYUrpPEYGvej2FpmuygKUKRDbltT74zj18Koy0FeVOkM6ifdMwE62h+oIPxF7OXmDeSL+JaJaLhOSyzG0nJBnMkvVOUXBPZ batisengul@kalidos-mbp.mynet

# Provide registry details: https://github.com/hasura/gitkube/blob/master/docs/registry.md
  registry:
    url: "rg.nl-ams.scw.cloud/njkonl"
    credentials:
      secretRef: regcred                # Name of docker-registry secret

# Define deployment rules
  deployments:
  - name: cv19pc                             # Name of K8s deployment which is updated on git push
    containers: 
    - name: cv19pc                           # Name of container in the deployment which is built during git push
      path: .                   # Docker build context path in the git repo
      dockerfile: Dockerfile  # Location of Dockerfile for the source code
