name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to registry
      run: docker login rg.nl-ams.scw.cloud/njkonl -u SCWQQ8SZH40EH0PCAVK9 -p ${{ secrets.SCR_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rg.nl-ams.scw.cloud/njkonl/covid19-per-capita:latest
    - name: Push the docker image
      run: docker push rg.nl-ams.scw.cloud/njkonl/covid19-per-capita:latest
